Resources:
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Region: "us-west-2"
      FunctionName: 'TestLambdaFunction'
      Runtime: 'nodejs14.x'
      Handler: 'index.handler'
      Code:
        S3Bucket: 'test-s3-bucket'
        S3Key: 'test-lambda-function.zip'
      Timeout: 5
      MemorySize: 128

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principle:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
    Policies:
      - PolicyName: 'LambdaExecutionPolicy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
          Resource: 'arn:aws:logs:*:*:*'  